version: '3.5'

services:
  scheduleserver:
    image: dulce/schedule-server:dev
    build:
      context: ../../
      dockerfile: Docker/Dev/Server/Dockerfile

  scheduleclient:
    image: dulce/schedule-client:dev
    build:
      context: ../../
      dockerfile: Docker/Dev/Client/Dockerfile
